#include "Ogre.h"
#include "OIS.h"

#include <XnVDeviceGenerator.h>
#include <XnVNite.h>
#include <vector>
//#include <MyUserControl.h>
#include <XnTypes.h>
#include <XnV3DVector.h>
#include <XnCppWrapper.h>
#include <XnVPointControl.h>
#include <OgreStringConverter.h>
#include <OgreErrorDialog.h>
#include "Hikari.h"
#include <math.h>
#include <XnCppWrapper.h>
#include "XnVDepthMessage.h"
#include <XnVHandPointContext.h>
#include "SamplePlugin.h"
#include <OgreCamera.h>
#include <OgreEntity.h>
#include <OgreLogManager.h>
#include <OgreRoot.h>
#include <OgreViewport.h>
#include <OgreSceneManager.h>
#include <OgreRenderWindow.h>
#include <OgreConfigFile.h>
#include "DotSceneLoader.hpp"
#include <OISEvents.h>
#include <OISInputManager.h>
#include <OISKeyboard.h>
#include <OISMouse.h>

#include <opencv\cv.h>
#include <opencv\cxcore.h>
#include <opencv\highgui.h>
#include <Terrain/OgreTerrain.h>
#include <Terrain/OgreTerrainGroup.h>
#include <Terrain/OgreTerrainMaterialGeneratorA.h>
#include <map>
#include <list>
#include <SdkTrays.h>
#include <SdkCameraMan.h>
#include <iostream>
#include <fstream>
#include <sys/types.h>
#include <errno.h>
#include <windows.h>
#include <tchar.h> 
#include <stdio.h>
#include <strsafe.h>
#include "FlashControl.h"
